name: Old single workflow

on: 
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: The repository to build from
        default: MilanKlausz/ncrystal_wheels
      branch:
        type: string
        description: The repository branch to use
        default: master
      do-deploy:
        type: boolean
        description: Do deploying to PyPI
        default: false
      #TODO add option to controll the platforms
      #TODO add option to upload to test pypy

  workflow_call:
    inputs:
      repository:
        type: string
        description: The repository to build from
        default: MilanKlausz/ncrystal_wheels
        required: true
      branch:
        type: string
        description: The repository branch to use
        default: master
        required: false
      do-deploy:
        type: boolean
        description: Do deploying to PyPI
        default: false
    secrets:
      pypi_password:
        required: false #required for pypi upload

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-12]
        os: [macos-12]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: cp38-*
          # CIBW_BUILD: cp{37,38,39,310,311}-*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    if: inputs.do-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          name: artifact
          path: dist

      - name: list artifact content
        run: |
          ls -l dist

      # - uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     user: __token__
      #     password: ${{ secrets.pypi_password }}
      #     repository_url: https://test.pypi.org/legacy/